Gensettings: Added fastd configuration support

diff --git a/gensettings b/gensettings
--- a/gensettings
+++ b/gensettings
@@ -407,6 +407,119 @@ Exec "nobody:nogroup" "/usr/sbin/collectd-mesh-script.sh"
 EOF
 }
 
+gen_fastdsettings() {
+	local fastd_config=$1
+	local fastd_peers_path=$2
+	local fastd_target_folder=$3
+	local fastd_uci_config=$4
+
+	# Include fastd config
+	. $fastd_config
+	# Check if fastd settings are non-zero strings and abort if thats not the case
+	[ -n "$fastd_registerserver" \
+	-a -n "$fastd_peers_path" \
+	-a -n "$fastd_meshvpn_mtu" \
+	-a -n "$fastd_meshvpn_methods" ] || fail "Error: One or more fastd settings are missing!"
+
+	# Remove old fastd folder if existing
+	[ -d $fastd_target_folder ] && rm -rf $fastd_target_folder
+	mkdir -p $fastd_target_folder
+
+	# Remove old uci config if existing
+	[ -f $fastd_uci_config ] && rm -f $fastd_uci_config
+
+	# Add mesh-vpn section to fastd UCI config
+	cat << EOF >> $fastd_uci_config
+config fastd mesh_vpn
+        option enabled 0
+        list config '/etc/fastd/mesh-vpn/fastd.conf'
+        list config_peer_dir '/etc/fastd/mesh-vpn/peers'
+        option syslog_level 'verbose'
+        option mode 'tap'
+        option interface 'mesh-vpn'
+        option mtu '$fastd_meshvpn_mtu'
+EOF
+
+		# Add encryption methods to fastd uci config
+		for method in $fastd_meshvpn_methods
+		do
+			echo "        list method '$method'" >> $fastd_uci_config
+		done
+
+		# Make peer folder recursivly if not existant
+		mkdir -p $fastd_target_folder/mesh-vpn/peers
+
+		# Add settings to fastd.conf
+		cat << EOF >> $fastd_target_folder/mesh-vpn/fastd.conf
+include "secret.conf";
+
+peer group "meshvpn" {
+        peer limit 2;
+        include peers from "peers";
+}
+
+on up "
+    batctl -m \"\$(uci -q get network.meshfsm.batman_iface)\" if add \$INTERFACE
+    exit 0
+";
+EOF
+
+		# Add peer files for mesh-vpn
+		for peer in $(find $fastd_peers_path/mesh-vpn -type f)
+		do
+			cp $peer $fastd_target_folder/mesh-vpn/peers
+		done
+		
+		
+		# Exit-VPN Part
+		if [ -n "$fastd_exitvpn_mtu" -a -n "$fastd_exitvpn_methods" ]; then
+			# Add exit-vpn section to fastd UCI config
+			cat << EOF >> $fastd_uci_config
+config fastd exit_vpn
+        option enabled 0
+        list config '/etc/fastd/exit-vpn/fastd.conf'
+        list config_peer_dir '/etc/fastd/exit-vpn/peers'
+        option syslog_level 'verbose'
+        option mode 'tap'
+        option interface 'exit-vpn'
+        option mtu '$fastd_exitvpn_mtu'
+EOF
+
+			# Add encryption methods to fastd uci config
+			for method in $fastd_exitvpn_methods
+			do
+				echo "        list method '$method'" >> $fastd_uci_config
+			done
+
+			# Make peer folder recursivly if not existant
+			mkdir -p $fastd_target_folder/exit-vpn/peers
+
+			# Add settings to fastd.conf
+			cat << EOF >> $fastd_target_folder/exit-vpn/fastd.conf
+include "secret.conf";
+
+peer group "exitvpn" {
+        peer limit 2;
+        include peers from "peers";
+}
+
+on up "
+    #Currently no automatic adding of the interface ;)
+    #batctl -m \"\$(uci -q get network.meshfsm.batman_iface)\" if add \$INTERFACE
+    exit 0
+";
+EOF
+
+			# Add peer files for exit-vpn
+			if [ -d $fastd_peers_path/exit-vpn ]; then
+				for peer in $(find $fastd_peers_path/exit-vpn -type f)
+				do
+					cp $peer $fastd_target_folder/exit-vpn/peers
+				done
+			fi
+		fi
+}
+
 gen_configs() {
 	local repository=$1
 	local buildtarget=$2
@@ -416,16 +529,19 @@ gen_configs() {
 	local wifi_config="config/communities/$community/wifi"
 	local splash_config="config/communities/$community/splash"
 	local n2n_config="config/communities/$community/n2n"
+	local fastd_config="config/communities/$community/fastd"
 	local collectd_config="config/communities/$community/collectd"
-	[ -f "$fsm_config" -a -f "$wifi_config" -a -f "$splash_config" -a -f "$n2n_config" ] || fail "Missing config files for community $community!"
+	[ -f "$fsm_config" -a -f "$wifi_config" -a -f "$splash_config" ] || fail "Missing config files for community $community!"
 	[ ! -d openwrt/$repository/ ] && fail "Error: Repository $repository not existant" 
 	[ ! -d openwrt/$repository/files/etc/defconfig ] && mkdir -p openwrt/$repository/files/etc/defconfig
+	[ ! -d openwrt/$repository/files/etc/config ] && mkdir -p openwrt/$repository/files/etc/config
 	
 	# Generate wireless config, returns the wifi dev for the ffpreconfigure config
 	adhoc_dev=$(gen_wifisettings $wifi_config openwrt/$repository/files/etc/config/wireless)
 	gen_fsmsettings "$fsm_config" "$adhoc_dev" "openwrt/$repository/files/etc/defconfig/ffpreconfigure"
 	gen_splashsettings "$splash_config" "openwrt/$repository/files/etc/config/splash"
-	gen_n2nsettings "$n2n_config" "openwrt/$repository/files/etc/config/n2n"
+	[ -f "$fastd_config" ] && gen_fastdsettings "$fastd_config" "config/communities/$community/fastd.peers" "openwrt/$repository/files/etc/fastd" "openwrt/$repository/files/etc/config/fastd" "openwrt/$repository/files/etc/config/fastdregister"
+	[ -f "$n2n_config" ] && gen_n2nsettings "$n2n_config" "openwrt/$repository/files/etc/config/n2n"
 	[ -f "$collectd_config" ] && gen_collectdsettings "$collectd_config" "openwrt/$repository/files/etc/collectd.conf"
 	exit 0
 }
